# noqa: N999 - automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()

class IndexFile:
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = IndexFile()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsIndexFile(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # IndexFile
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IndexFile
    def Codename(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # IndexFile
    def NumArchives(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # IndexFile
    def XxhashSeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # IndexFile
    def ArchiveFileHashes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # IndexFile
    def ArchiveFileHashesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # IndexFile
    def ArchiveFileHashesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndexFile
    def ArchiveFileHashesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # IndexFile
    def FileToChunkIndexers(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from GBFRDataTools.FlatBuffers.FileToChunkIndexer import FileToChunkIndexer
            obj = FileToChunkIndexer()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IndexFile
    def FileToChunkIndexersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndexFile
    def FileToChunkIndexersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # IndexFile
    def Chunks(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 24
            from GBFRDataTools.FlatBuffers.DataChunk import DataChunk
            obj = DataChunk()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # IndexFile
    def ChunksLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndexFile
    def ChunksIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # IndexFile
    def ExternalFileHashes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # IndexFile
    def ExternalFileHashesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # IndexFile
    def ExternalFileHashesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndexFile
    def ExternalFileHashesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # IndexFile
    def ExternalFileSizes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # IndexFile
    def ExternalFileSizesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # IndexFile
    def ExternalFileSizesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndexFile
    def ExternalFileSizesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # IndexFile
    def CachedChunkIndices(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # IndexFile
    def CachedChunkIndicesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # IndexFile
    def CachedChunkIndicesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # IndexFile
    def CachedChunkIndicesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

def IndexFileStart(builder):
    builder.StartObject(9)

def Start(builder):
    IndexFileStart(builder)

def IndexFileAddCodename(builder, codename):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(codename), 0)

def AddCodename(builder, codename):
    IndexFileAddCodename(builder, codename)

def IndexFileAddNumArchives(builder, numArchives):
    builder.PrependUint16Slot(1, numArchives, 0)

def AddNumArchives(builder, numArchives):
    IndexFileAddNumArchives(builder, numArchives)

def IndexFileAddXxhashSeed(builder, xxhashSeed):
    builder.PrependUint16Slot(2, xxhashSeed, 0)

def AddXxhashSeed(builder, xxhashSeed):
    IndexFileAddXxhashSeed(builder, xxhashSeed)

def IndexFileAddArchiveFileHashes(builder, archiveFileHashes):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(archiveFileHashes), 0)

def AddArchiveFileHashes(builder, archiveFileHashes):
    IndexFileAddArchiveFileHashes(builder, archiveFileHashes)

def IndexFileStartArchiveFileHashesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartArchiveFileHashesVector(builder, numElems):
    return IndexFileStartArchiveFileHashesVector(builder, numElems)

def IndexFileCreateArchiveFileHashesVector(builder, data):
    data = list(data)
    builder.StartVector(8, len(data), 8)
    for item in reversed(data):
        builder.PrependUint64(item)
    return builder.EndVector()

def CreateArchiveFileHashesVector(builder, data):
    return IndexFileCreateArchiveFileHashesVector(builder, data)

def IndexFileAddFileToChunkIndexers(builder, fileToChunkIndexers):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(fileToChunkIndexers), 0)

def AddFileToChunkIndexers(builder, fileToChunkIndexers):
    IndexFileAddFileToChunkIndexers(builder, fileToChunkIndexers)

def IndexFileStartFileToChunkIndexersVector(builder, numElems):
    return builder.StartVector(12, numElems, 4)

def StartFileToChunkIndexersVector(builder, numElems):
    return IndexFileStartFileToChunkIndexersVector(builder, numElems)

def IndexFileCreateFileToChunkIndexersVector(builder, data):
    data = list(data)
    builder.StartVector(12, len(data), 4)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateFileToChunkIndexersVector(builder, data):
    return IndexFileCreateFileToChunkIndexersVector(builder, data)

def IndexFileAddChunks(builder, chunks):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(chunks), 0)

def AddChunks(builder, chunks):
    IndexFileAddChunks(builder, chunks)

def IndexFileStartChunksVector(builder, numElems):
    return builder.StartVector(24, numElems, 8)

def StartChunksVector(builder, numElems):
    return IndexFileStartChunksVector(builder, numElems)

def IndexFileCreateChunksVector(builder, data):
    data = list(data)
    builder.StartVector(24, len(data), 8)
    for item in reversed(data):
        item.Pack(builder)
    return builder.EndVector()

def CreateChunksVector(builder, data):
    return IndexFileCreateChunksVector(builder, data)

def IndexFileAddExternalFileHashes(builder, externalFileHashes):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(externalFileHashes), 0)

def AddExternalFileHashes(builder, externalFileHashes):
    IndexFileAddExternalFileHashes(builder, externalFileHashes)

def IndexFileStartExternalFileHashesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartExternalFileHashesVector(builder, numElems):
    return IndexFileStartExternalFileHashesVector(builder, numElems)

def IndexFileCreateExternalFileHashesVector(builder, data):
    data = list(data)
    builder.StartVector(8, len(data), 8)
    for item in reversed(data):
        builder.PrependUint64(item)
    return builder.EndVector()

def CreateExternalFileHashesVector(builder, data):
    return IndexFileCreateExternalFileHashesVector(builder, data)

def IndexFileAddExternalFileSizes(builder, externalFileSizes):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(externalFileSizes), 0)

def AddExternalFileSizes(builder, externalFileSizes):
    IndexFileAddExternalFileSizes(builder, externalFileSizes)

def IndexFileStartExternalFileSizesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartExternalFileSizesVector(builder, numElems):
    return IndexFileStartExternalFileSizesVector(builder, numElems)

def IndexFileCreateExternalFileSizesVector(builder, data):
    data = list(data)
    builder.StartVector(8, len(data), 8)
    for item in reversed(data):
        builder.PrependUint64(item)
    return builder.EndVector()

def CreateExternalFileSizesVector(builder, data):
    return IndexFileCreateExternalFileSizesVector(builder, data)

def IndexFileAddCachedChunkIndices(builder, cachedChunkIndices):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(cachedChunkIndices), 0)

def AddCachedChunkIndices(builder, cachedChunkIndices):
    IndexFileAddCachedChunkIndices(builder, cachedChunkIndices)

def IndexFileStartCachedChunkIndicesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCachedChunkIndicesVector(builder, numElems):
    return IndexFileStartCachedChunkIndicesVector(builder, numElems)

def IndexFileCreateCachedChunkIndicesVector(builder, data):
    data = list(data)
    builder.StartVector(4, len(data), 4)
    for item in reversed(data):
        builder.PrependUint32(item)
    return builder.EndVector()

def CreateCachedChunkIndicesVector(builder, data):
    return IndexFileCreateCachedChunkIndicesVector(builder, data)

def IndexFileEnd(builder):
    return builder.EndObject()

def End(builder):
    return IndexFileEnd(builder)
