"""Shared helpers: vendor bootstrap, game directory detection, data loading."""
import gzip
import hashlib
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VENDOR_DIR = os.path.join(REPO_ROOT, "vendor")
DATA_DIR = os.path.join(REPO_ROOT, "data")

TEXT_KO = "data/system/table/text/ko"
SCENARIO_KO = "data/system/table/scenario/ko"


def table_rel(file):
    """Relative game dir holding a given .msg table."""
    return SCENARIO_KO if file.startswith("text_scenario") else TEXT_KO


# gbfr_schema is generated by the FlatBuffers compiler; the runtime flatbuffers
# must match the version it was generated against. Keep in sync with
# vendor/README.md and scripts/update_vendor.sh.
FLATBUFFERS_PIN = "25.12.19"


def bootstrap():
    """Wire up third-party dependencies: prefer pip when available.

    ``vendor/`` is appended (not prepended) so a pip install of the pinned
    versions wins over the bundled pure-Python copies; without pip the
    vendored copies are the zero-install fallback. The one exception is
    flatbuffers: ``gbfr_schema`` is generated by flatc ``FLATBUFFERS_PIN``,
    so when the pip copy drifts from that pin the vendored copy is forced
    into ``sys.modules`` instead of the drifting install.
    """
    if VENDOR_DIR not in sys.path:
        sys.path.append(VENDOR_DIR)
    try:
        import flatbuffers as _fb
    except ImportError:
        return
    if getattr(_fb, "__version__", None) != FLATBUFFERS_PIN:
        from importlib import util as _util
        for _name in [n for n in sys.modules
                      if n == "flatbuffers" or n.startswith("flatbuffers.")]:
            del sys.modules[_name]
        _root = os.path.join(VENDOR_DIR, "flatbuffers")
        _spec = _util.spec_from_file_location(
            "flatbuffers", os.path.join(_root, "__init__.py"),
            submodule_search_locations=[_root])
        assert _spec is not None
        assert _spec.loader is not None
        _mod = _util.module_from_spec(_spec)
        _spec.loader.exec_module(_mod)
        sys.modules["flatbuffers"] = _mod


def repo_file(name):
    return os.path.join(REPO_ROOT, name)


def load_translations():
    with open(repo_file("translations.json"), encoding="utf-8") as f:
        return json.load(f)


def check_version(game_dir, fingerprint=None):
    """Compare the English sources of `game_dir` against the build fingerprint
    stored in translations.json. Returns (ok, mismatches, checked).

    Used to warn that the translation table may not match a newer game build.
    """
    if fingerprint is None:
        fingerprint = load_translations()["meta"].get("build_fingerprint", {})
    if not fingerprint:
        return True, [], 0
    try:
        from extract import extract
    except ImportError:
        return True, [], 0
    mismatches = []
    checked = 0
    for path, expected in fingerprint.items():
        data = extract(game_dir, path)
        checked += 1
        if data is None:
            mismatches.append((path, expected, "<not found>"))
            continue
        actual = hashlib.md5(data).hexdigest()
        if actual != expected:
            mismatches.append((path, expected, actual))
    return not mismatches, mismatches, checked


def load_filelist():
    """Load the internal file-path list (hash -> path mapping).

    Priority:
      1. $GBFR_FILELIST - a plain-text filelist from GBFRDataTools (fresh
         copy for a newer game build)
      2. bundled data/filelist.txt.gz
    """
    path = os.environ.get("GBFR_FILELIST")
    if path and os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            return f.read().splitlines()
    with gzip.open(os.path.join(DATA_DIR, "filelist.txt.gz"), "rt", encoding="utf-8") as f:
        return f.read().splitlines()


# Candidate roots where a GBF Relink install may live.
def _candidate_roots():
    roots = []
    if sys.platform == "win32":
        for letter in "CDEF":
            roots.append(f"{letter}:\\")
    else:
        for base in ("/mnt", "/run/media"):
            try:
                for entry in sorted(os.listdir(base)):
                    roots.append(os.path.join(base, entry))
            except OSError:
                pass
        roots += [
            os.path.expanduser("~/.local/share/Steam/steamapps/common"),
            os.path.expanduser("~/.steam/steam/steamapps/common"),
        ]
    return roots


def find_game_dir():
    """Locate a directory that looks like a GBF Relink install (has data.i
    and the loose text tables). Returns path or None.

    Depth-limited so it never hangs scanning an entire drive (important on
    Windows); the gfrpatch module only uses this as a hint and asks the
    user for the path anyway.
    """
    hint = os.environ.get("GBFR_GAME")
    if hint and os.path.isfile(os.path.join(hint, "data.i")):
        return hint
    skip = {".", "..", "Windows", "Program Files", "Program Files (x86)",
            "Users", "$Recycle.Bin", "System Volume Information", "Recovery",
            "AppData", ".cache", "__pycache__"}
    for root in _candidate_roots():
        for dirpath, dirnames, filenames in os.walk(root):
            depth = dirpath[len(root):].count(os.sep)
            if "data.i" in filenames and dirpath.endswith("Granblue Fantasy - Relink"):
                return dirpath
            if depth >= 8:
                dirnames[:] = []
                continue
            dirnames[:] = [d for d in dirnames if d not in skip]
    return None
